name: Run biome to check code
run-name: Check quality of code - triggered by @${{ github.actor }}

on:
  workflow_dispatch:      
  pull_request:
    branches: main
    paths:
      - "client/**"
      - "server/**"

jobs:
  biome-checks:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
          
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
          
      - name: Run Biome checks
        run: biome ci --reporter=github client server
